TO-DO-LIST Add&Remove
Suzi216/To-Do-List pull request #3
Opened 2022-08-12 16:33 UTC by Suzi216

**To Do list: add & remove**

For this project I have done all these requirements:

- Created a new JavaScript files for the new functionality.

- Implemented a function for adding a new task in the array.

- Implemented a function for deleting a task from the array.

- Implemented a function for editing task descriptions.

- All changes to the To Do List are saved in local storage.

2022-08-12 16:52 UTC, zainsadaqat requested changes
# Required Changes 🔁
# Hello @Suzi216  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-12 16:52 UTC, zainsadaqat commented on src/modulus/addlist.js
> +  if (localStorage.getItem('ls') === null) {
When I refresh the page, All added todo items get disappeared although the items are still in the local storage. Kindly fix this issues.
#### Screenshot
<img width="1409" alt="Screenshot 2022-08-12 at 9 48 26 PM" src="https://user-images.githubusercontent.com/83048208/184405824-a987e2e4-e45f-4692-8835-de13e60ef682.png">

2022-08-12 16:52 UTC, zainsadaqat commented on src/modulus/editD.js
> +};
Edit feature isn't working. It does show that I've edited a todo item but changes are not reflected to the local storage. There's still old todo item although I already edited that on the interface. Kindly fix this issue 👍🏻 
#### Screenshot
<img width="1409" alt="Screenshot 2022-08-12 at 9 51 19 PM" src="https://user-images.githubusercontent.com/83048208/184406287-6411bfff-bce9-4b46-bd48-5fb34f440a48.png">

2022-08-13 10:11 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @Suzi216, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean/Organized code

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-13 10:26 UTC, merged